package validation

var defaultErrors = map[string]string{
	"required":                        "REQUIRED_ATTRIBUTE_MISSING",
	"invalid_type":                    "INVALID_DATA_TYPE",
	"number_any_of":                   "INVALID_DATA_TYPE",
	"number_one_of":                   "INVALID_DATA_TYPE",
	"number_all_of":                   "INVALID_DATA_TYPE",
	"number_not":                      "INVALID_DATA_TYPE",
	"missing_dependency":              "INVALID_DATA_TYPE",
	"internal":                        "INVALID_DATA_TYPE",
	"const":                           "INVALID_DATA_TYPE",
	"enum":                            "INVALID_VALUE",
	"array_no_additional_items":       "INVALID_DATA_TYPE",
	"array_min_items":                 "INVALID_DATA_TYPE",
	"array_max_items":                 "INVALID_DATA_TYPE",
	"unique":                          "INVALID_DATA_TYPE",
	"contains":                        "INVALID_DATA_TYPE",
	"array_min_properties":            "INVALID_DATA_TYPE",
	"array_max_properties":            "INVALID_DATA_TYPE",
	"additional_property_not_allowed": "INVALID_DATA_TYPE",
	"invalid_property_pattern":        "INVALID_DATA_TYPE",
	"invalid_property_name":           "INVALID_DATA_TYPE",
	"string_gte":                      "INVALID_LENGTH",
	"string_lte":                      "INVALID_LENGTH",
	"pattern":                         "INVALID_DATA_TYPE",
	"multiple_of":                     "INVALID_DATA_TYPE",
	"number_gte":                      "INVALID_VALUE",
	"number_gt":                       "INVALID_VALUE",
	"number_lte":                      "INVALID_VALUE",
	"number_lt":                       "INVALID_VALUE",
	"condition_then":                  "INVALID_DATA_TYPE",
	"condition_else":                  "INVALID_DATA_TYPE",
	"format":                          "INVALID_FORMAT",
}
